{"name": "test_001_login_success[test1234-test1234-\\u767b\\u5f55\\u6210\\u529f1]", "status": "broken", "statusDetails": {"message": "NameError: name 'python_obj' is not defined", "trace": "self = <testcase.test01_login.TestLogin object at 0x1026ad8d0>\nuname = 'test1234', upwd = 'test1234', expect = '登录成功'\n\n    @pytest.mark.parametrize(\"uname, upwd, expect\", utils.get_login_data_by_excel(2, 3))\n    # 定义日志级别为CRITICAL\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_001_login_success(self, uname, upwd, expect):\n        logging.info(\"用例输入数据如下：用户名：{}，密码：{}，预期结果：{}\".format(uname, upwd, expect))\n        # 发送请求附带数据\n        json_data = {\"uname\": uname, \"upwd\": upwd}\n>       response = self.login_api.login(json_data)\n\ntest01_login.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api.login.login.LoginAPI object at 0x10269e0d0>\njson_data = {'uname': 'test1234', 'upwd': 'test1234'}\n\n    def login(self, json_data):\n    \n>       return requests.post(url=self.url_login, json=python_obj, verify=False)\nE       NameError: name 'python_obj' is not defined\n\n../api/login/login.py:20: NameError"}, "parameters": [{"name": "uname", "value": "'test1234'"}, {"name": "upwd", "value": "'test1234'"}, {"name": "expect", "value": "'登录成功'"}], "start": 1710171078940, "stop": 1710171078941, "uuid": "e2969653-fd00-488a-bfb6-5e606df54c86", "historyId": "6261ef6205cdb334abd6178168c8e559", "testCaseId": "5e617d0a494d476c894db1d54060c1ec", "fullName": "testcase.test01_login.TestLogin#test_001_login_success", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test01_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "hkdeMacBook-Pro"}, {"name": "thread", "value": "65404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test01_login"}]}